version: '3.8'
services:
  # ----------------------------------------------------
  # Servicio de Base de Datos MySQL
  # ----------------------------------------------------
  db-mysql:
    image: mysql:8.0
    container_name: db-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - servipark-mysql-data:/var/lib/mysql

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 5s
      timeout: 10s
      retries: 10
      start_period: 20s

  # ----------------------------------------------------
  # Servicio de Aplicación Spring Boot
  # ----------------------------------------------------
  app-servipark:
    build: .
    container_name: app-servipark
    restart: unless-stopped
    ports:
      - "8080:8080"

    depends_on:
      db-mysql:
        condition: service_healthy

    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db-mysql:3306/servipark_db?useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}

volumes:
  servipark-mysql-data: